[api]
enabled = true


[sources.vectorlogs]
type = "internal_logs"

[sinks.loki_vectorlogs]
type = "loki"
inputs = ["vectorlogs"]
encoding.codec = "json"
endpoint = "http://loki:3100"
labels.logsource = "vector"


[sources.dockersyslog]
type = "syslog"
address = "0.0.0.0:5123"
mode = "udp"

[sinks.loki_dockersyslog]
type = "loki"
inputs = ["dockersyslog"]
encoding.codec = "json"
endpoint = "http://loki:3100"
labels.logsource = "docker"
